### ISSUE TITLE
Cannot find module 'bson-json-reader'

### ISSUE THREAD

**Issue by sophieyoung717** [danielgindi/node-bson-json-transform#1]
Hi, 

I tried your example.

var fs = require('fs');
var BsonJsonTransform = require('bson-json-reader');

fs
    .createReadStream('users.bson')
    .pipe(BsonJsonTransform({ preserveInt64: 'string' }))
    .pipe(fs.createWriteStream('users.json'))
    .on('end', function (data) {
        console.log('No more data!');
    });

The error is:
Error: Cannot find module 'bson-json-reader'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by danielgindi** [comment]
It's 'bson-json-transform' :-)

**Comment by linslin** [comment]
Please update your docu at `var BsonJsonTransform = require('bson-json-reader');` in readme.md.
