### ISSUE TITLE
transform raw cursor from Mongo Oplog

### ISSUE THREAD

**Issue by ORESoftware** [danielgindi/node-bson-json-transform#4]
Using `require('mongodb')`, I have this:

```js
      const q = coll.find(query, {
        raw: true,
        tailable: true,
        awaitData: true,
        oplogReplay: true,
        noCursorTimeout: true,
        numberOfRetries: Number.MAX_VALUE
      });
      
      const changeStream = q.stream();
```

changeStream is a Readable stream that now sends what looks to be binary. That is because I have used the `raw:true` option.

Is this package a good one to convert the BSON from the above stream to JSON? More importantly, is there an option I can use with this librarty to convert from BSON to JS objects instead of BSON -> JSON?

I am looking for a way to do both:

BSON-> JSON
BSON-> JS objects

thanks

**Comment by ORESoftware** [comment]
also, since you may know a lot about streams - do you know if a transform stream can accept a JS object instead of a string/buffer?

https://stackoverflow.com/questions/49328510/transform-js-objects-to-json-using-transform-stream

**Comment by danielgindi** [comment]
Hi!

Yes, this stream expects a binary input stream of BSON.

JSON is basically JS objects. So you requirements are one and the same.
If you want the JSON as a string, that's a different matter and you'll have to use `JSON.stringify(...)` on the output.

And yes, in streams there's an `objectMode` property, when true - the transform expects object.
https://nodejs.org/api/stream.html

> All streams created by Node.js APIs operate exclusively on strings and Buffer (or Uint8Array) objects. It is possible, however, for stream implementations to work with other types of JavaScript values (with the exception of null, which serves a special purpose within streams). Such streams are considered to operate in "object mode".
>
>Stream instances are switched into object mode using the objectMode option when the stream is created. Attempting to switch an existing stream into object mode is not safe.

**Comment by ORESoftware** [comment]
ok cool thanks, I might use this package
